// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.tutorial.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string firstname = 1;</code>
     */
    boolean hasFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>optional string lastname = 2;</code>
     */
    boolean hasLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>required int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    boolean hasSalary();
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    double getSalary();

    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    java.util.List<com.tutorial.protobuf.EmployeeProto.Department> 
        getDeptList();
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    com.tutorial.protobuf.EmployeeProto.Department getDept(int index);
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    int getDeptCount();
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    java.util.List<? extends com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList();
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Employee)
      EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      firstname_ = "";
      lastname_ = "";
      id_ = 0;
      salary_ = 100000D;
      dept_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastname_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              salary_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                dept_ = new java.util.ArrayList<com.tutorial.protobuf.EmployeeProto.Department>();
                mutable_bitField0_ |= 0x00000010;
              }
              dept_.add(
                  input.readMessage(com.tutorial.protobuf.EmployeeProto.Department.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = java.util.Collections.unmodifiableList(dept_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.EmployeeProto.Employee.class, com.tutorial.protobuf.EmployeeProto.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstname_;
    /**
     * <code>required string firstname = 1;</code>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastname_;
    /**
     * <code>optional string lastname = 2;</code>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>required int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public double getSalary() {
      return salary_;
    }

    public static final int DEPT_FIELD_NUMBER = 5;
    private java.util.List<com.tutorial.protobuf.EmployeeProto.Department> dept_;
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    public java.util.List<com.tutorial.protobuf.EmployeeProto.Department> getDeptList() {
      return dept_;
    }
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    public java.util.List<? extends com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList() {
      return dept_;
    }
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    public int getDeptCount() {
      return dept_.size();
    }
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    public com.tutorial.protobuf.EmployeeProto.Department getDept(int index) {
      return dept_.get(index);
    }
    /**
     * <code>repeated .tutorial.Department dept = 5;</code>
     */
    public com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index) {
      return dept_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFirstname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDeptCount(); i++) {
        if (!getDept(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        output.writeMessage(5, dept_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, dept_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tutorial.protobuf.EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      com.tutorial.protobuf.EmployeeProto.Employee other = (com.tutorial.protobuf.EmployeeProto.Employee) obj;

      boolean result = true;
      result = result && (hasFirstname() == other.hasFirstname());
      if (hasFirstname()) {
        result = result && getFirstname()
            .equals(other.getFirstname());
      }
      result = result && (hasLastname() == other.hasLastname());
      if (hasLastname()) {
        result = result && getLastname()
            .equals(other.getLastname());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasSalary() == other.hasSalary());
      if (hasSalary()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSalary())
            == java.lang.Double.doubleToLongBits(
                other.getSalary()));
      }
      result = result && getDeptList()
          .equals(other.getDeptList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFirstname()) {
        hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstname().hashCode();
      }
      if (hasLastname()) {
        hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastname().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasSalary()) {
        hash = (37 * hash) + SALARY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSalary()));
      }
      if (getDeptCount() > 0) {
        hash = (37 * hash) + DEPT_FIELD_NUMBER;
        hash = (53 * hash) + getDeptList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tutorial.protobuf.EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Employee)
        com.tutorial.protobuf.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.EmployeeProto.Employee.class, com.tutorial.protobuf.EmployeeProto.Employee.Builder.class);
      }

      // Construct using com.tutorial.protobuf.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDeptFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        firstname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        salary_ = 100000D;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          deptBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Employee_descriptor;
      }

      public com.tutorial.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
        return com.tutorial.protobuf.EmployeeProto.Employee.getDefaultInstance();
      }

      public com.tutorial.protobuf.EmployeeProto.Employee build() {
        com.tutorial.protobuf.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.EmployeeProto.Employee buildPartial() {
        com.tutorial.protobuf.EmployeeProto.Employee result = new com.tutorial.protobuf.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstname_ = firstname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastname_ = lastname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.salary_ = salary_;
        if (deptBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            dept_ = java.util.Collections.unmodifiableList(dept_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.dept_ = dept_;
        } else {
          result.dept_ = deptBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.EmployeeProto.Employee) {
          return mergeFrom((com.tutorial.protobuf.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.EmployeeProto.Employee other) {
        if (other == com.tutorial.protobuf.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.hasFirstname()) {
          bitField0_ |= 0x00000001;
          firstname_ = other.firstname_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000002;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        if (deptBuilder_ == null) {
          if (!other.dept_.isEmpty()) {
            if (dept_.isEmpty()) {
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureDeptIsMutable();
              dept_.addAll(other.dept_);
            }
            onChanged();
          }
        } else {
          if (!other.dept_.isEmpty()) {
            if (deptBuilder_.isEmpty()) {
              deptBuilder_.dispose();
              deptBuilder_ = null;
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
              deptBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDeptFieldBuilder() : null;
            } else {
              deptBuilder_.addAllMessages(other.dept_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstname()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        for (int i = 0; i < getDeptCount(); i++) {
          if (!getDept(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstname_ = "";
      /**
       * <code>required string firstname = 1;</code>
       */
      public boolean hasFirstname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder clearFirstname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>optional string lastname = 2;</code>
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      private double salary_ = 100000D;
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public boolean hasSalary() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder setSalary(double value) {
        bitField0_ |= 0x00000008;
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 100000D;
        onChanged();
        return this;
      }

      private java.util.List<com.tutorial.protobuf.EmployeeProto.Department> dept_ =
        java.util.Collections.emptyList();
      private void ensureDeptIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = new java.util.ArrayList<com.tutorial.protobuf.EmployeeProto.Department>(dept_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tutorial.protobuf.EmployeeProto.Department, com.tutorial.protobuf.EmployeeProto.Department.Builder, com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder> deptBuilder_;

      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public java.util.List<com.tutorial.protobuf.EmployeeProto.Department> getDeptList() {
        if (deptBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dept_);
        } else {
          return deptBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public int getDeptCount() {
        if (deptBuilder_ == null) {
          return dept_.size();
        } else {
          return deptBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public com.tutorial.protobuf.EmployeeProto.Department getDept(int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);
        } else {
          return deptBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder setDept(
          int index, com.tutorial.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.set(index, value);
          onChanged();
        } else {
          deptBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder setDept(
          int index, com.tutorial.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.set(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder addDept(com.tutorial.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(value);
          onChanged();
        } else {
          deptBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder addDept(
          int index, com.tutorial.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(index, value);
          onChanged();
        } else {
          deptBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder addDept(
          com.tutorial.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder addDept(
          int index, com.tutorial.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder addAllDept(
          java.lang.Iterable<? extends com.tutorial.protobuf.EmployeeProto.Department> values) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dept_);
          onChanged();
        } else {
          deptBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder clearDept() {
        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          deptBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public Builder removeDept(int index) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.remove(index);
          onChanged();
        } else {
          deptBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public com.tutorial.protobuf.EmployeeProto.Department.Builder getDeptBuilder(
          int index) {
        return getDeptFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
          int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);  } else {
          return deptBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public java.util.List<? extends com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder> 
           getDeptOrBuilderList() {
        if (deptBuilder_ != null) {
          return deptBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dept_);
        }
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public com.tutorial.protobuf.EmployeeProto.Department.Builder addDeptBuilder() {
        return getDeptFieldBuilder().addBuilder(
            com.tutorial.protobuf.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public com.tutorial.protobuf.EmployeeProto.Department.Builder addDeptBuilder(
          int index) {
        return getDeptFieldBuilder().addBuilder(
            index, com.tutorial.protobuf.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Department dept = 5;</code>
       */
      public java.util.List<com.tutorial.protobuf.EmployeeProto.Department.Builder> 
           getDeptBuilderList() {
        return getDeptFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tutorial.protobuf.EmployeeProto.Department, com.tutorial.protobuf.EmployeeProto.Department.Builder, com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder> 
          getDeptFieldBuilder() {
        if (deptBuilder_ == null) {
          deptBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tutorial.protobuf.EmployeeProto.Department, com.tutorial.protobuf.EmployeeProto.Department.Builder, com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder>(
                  dept_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          dept_ = null;
        }
        return deptBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Employee)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Employee)
    private static final com.tutorial.protobuf.EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorial.protobuf.EmployeeProto.Employee();
    }

    public static com.tutorial.protobuf.EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    public com.tutorial.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DepartmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Department)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 deptid = 1;</code>
     */
    boolean hasDeptid();
    /**
     * <code>required int32 deptid = 1;</code>
     */
    int getDeptid();

    /**
     * <code>required string deptname = 2;</code>
     */
    boolean hasDeptname();
    /**
     * <code>required string deptname = 2;</code>
     */
    java.lang.String getDeptname();
    /**
     * <code>required string deptname = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeptnameBytes();
  }
  /**
   * Protobuf type {@code tutorial.Department}
   */
  public  static final class Department extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Department)
      DepartmentOrBuilder {
    // Use Department.newBuilder() to construct.
    private Department(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Department() {
      deptid_ = 0;
      deptname_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Department(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deptid_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deptname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Department_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Department_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.EmployeeProto.Department.class, com.tutorial.protobuf.EmployeeProto.Department.Builder.class);
    }

    private int bitField0_;
    public static final int DEPTID_FIELD_NUMBER = 1;
    private int deptid_;
    /**
     * <code>required int32 deptid = 1;</code>
     */
    public boolean hasDeptid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 deptid = 1;</code>
     */
    public int getDeptid() {
      return deptid_;
    }

    public static final int DEPTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object deptname_;
    /**
     * <code>required string deptname = 2;</code>
     */
    public boolean hasDeptname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string deptname = 2;</code>
     */
    public java.lang.String getDeptname() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deptname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deptname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeptnameBytes() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deptname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeptid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeptname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deptid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deptname_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deptid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deptname_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tutorial.protobuf.EmployeeProto.Department)) {
        return super.equals(obj);
      }
      com.tutorial.protobuf.EmployeeProto.Department other = (com.tutorial.protobuf.EmployeeProto.Department) obj;

      boolean result = true;
      result = result && (hasDeptid() == other.hasDeptid());
      if (hasDeptid()) {
        result = result && (getDeptid()
            == other.getDeptid());
      }
      result = result && (hasDeptname() == other.hasDeptname());
      if (hasDeptname()) {
        result = result && getDeptname()
            .equals(other.getDeptname());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeptid()) {
        hash = (37 * hash) + DEPTID_FIELD_NUMBER;
        hash = (53 * hash) + getDeptid();
      }
      if (hasDeptname()) {
        hash = (37 * hash) + DEPTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeptname().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorial.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tutorial.protobuf.EmployeeProto.Department prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Department}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Department)
        com.tutorial.protobuf.EmployeeProto.DepartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Department_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Department_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.EmployeeProto.Department.class, com.tutorial.protobuf.EmployeeProto.Department.Builder.class);
      }

      // Construct using com.tutorial.protobuf.EmployeeProto.Department.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deptid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deptname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.EmployeeProto.internal_static_tutorial_Department_descriptor;
      }

      public com.tutorial.protobuf.EmployeeProto.Department getDefaultInstanceForType() {
        return com.tutorial.protobuf.EmployeeProto.Department.getDefaultInstance();
      }

      public com.tutorial.protobuf.EmployeeProto.Department build() {
        com.tutorial.protobuf.EmployeeProto.Department result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.EmployeeProto.Department buildPartial() {
        com.tutorial.protobuf.EmployeeProto.Department result = new com.tutorial.protobuf.EmployeeProto.Department(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deptid_ = deptid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deptname_ = deptname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.EmployeeProto.Department) {
          return mergeFrom((com.tutorial.protobuf.EmployeeProto.Department)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.EmployeeProto.Department other) {
        if (other == com.tutorial.protobuf.EmployeeProto.Department.getDefaultInstance()) return this;
        if (other.hasDeptid()) {
          setDeptid(other.getDeptid());
        }
        if (other.hasDeptname()) {
          bitField0_ |= 0x00000002;
          deptname_ = other.deptname_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeptid()) {
          return false;
        }
        if (!hasDeptname()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.EmployeeProto.Department parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.EmployeeProto.Department) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int deptid_ ;
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public boolean hasDeptid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public int getDeptid() {
        return deptid_;
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public Builder setDeptid(int value) {
        bitField0_ |= 0x00000001;
        deptid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public Builder clearDeptid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deptid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deptname_ = "";
      /**
       * <code>required string deptname = 2;</code>
       */
      public boolean hasDeptname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public java.lang.String getDeptname() {
        java.lang.Object ref = deptname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deptname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeptnameBytes() {
        java.lang.Object ref = deptname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deptname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder setDeptname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deptname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder clearDeptname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deptname_ = getDefaultInstance().getDeptname();
        onChanged();
        return this;
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder setDeptnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deptname_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Department)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Department)
    private static final com.tutorial.protobuf.EmployeeProto.Department DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorial.protobuf.EmployeeProto.Department();
    }

    public static com.tutorial.protobuf.EmployeeProto.Department getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Department>
        PARSER = new com.google.protobuf.AbstractParser<Department>() {
      public Department parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Department(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Department> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Department> getParserForType() {
      return PARSER;
    }

    public com.tutorial.protobuf.EmployeeProto.Department getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Department_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Department_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\010tutorial\"w\n\010Employee\022\021" +
      "\n\tfirstname\030\001 \002(\t\022\020\n\010lastname\030\002 \001(\t\022\n\n\002i" +
      "d\030\003 \002(\005\022\026\n\006salary\030\004 \001(\001:\006100000\022\"\n\004dept\030" +
      "\005 \003(\0132\024.tutorial.Department\".\n\nDepartmen" +
      "t\022\016\n\006deptid\030\001 \002(\005\022\020\n\010deptname\030\002 \002(\tB&\n\025c" +
      "om.tutorial.protobufB\rEmployeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Employee_descriptor,
        new java.lang.String[] { "Firstname", "Lastname", "Id", "Salary", "Dept", });
    internal_static_tutorial_Department_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Department_descriptor,
        new java.lang.String[] { "Deptid", "Deptname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
